### ISSUE TITLE
Support and test password and maxPlayers protected lobbies

### ISSUE THREAD

**Issue by koenbollen** [poki/netlib#86]
There are signs of a password fields in the API and client but it's not yet supported completely. We need to fix this.

**Comment by koenbollen** [comment]
Same for maxPlayers

**Comment by aglitchman** [comment]
> Same for maxPlayers

I have a request: leave the ability for the lobby creator to enter the game, even if max players has already reached the limit.

In my project now architecturally the main “server” is the player who created the game. If he closed the game - the game stops (for players it's OK). If he closed accidentally and wants to come back, then you need your server to let him do that and not restrict access due to max players limit.

**Comment by koenbollen** [comment]
> > Same for maxPlayers
> 
> I have a request: leave the ability for the lobby creator to enter the game, even if max players has already reached the limit.
> 
> In my project now architecturally the main “server” is the player who created the game. If he closed the game - the game stops (for players it's OK). If he closed accidentally and wants to come back, then you need your server to let him do that and not restrict access due to max players limit.

When we would enforce the maxPlayers you could implement this usecase yourself using filters:
Set the limit to 7 instead of 6. Filter on `playerCount <= 6` when showing lobbies to other players. The creator of the lobby still has the code to join and will still fit.

We'll have a look when implementing maxPlayers if there is an easy fit for this, but we don't want to make to many exception to the rules to keep it simple and general.

**Comment by aglitchman** [comment]
> Set the limit to 7 instead of 6.

Brilliant! I got the point 🙌🏻

**Comment by erikdubbelboer** [comment]
This has been supported since the last release.
